/**
 * CyberNexsus Edge AI SOC - Telegram Notification & Dispatch Service
 * Sends formatted incident alerts and investigation summaries directly to Telegram.
 */

import { SecurityAlert, TelegramConfig, TelegramDispatchLog } from '../types';

export const DEFAULT_TELEGRAM_CONFIG: TelegramConfig = {
  enabled: true,
  botToken: '',
  chatId: '',
  autoDispatchCritical: true,
  autoDispatchHigh: false,
  includeCvssDetails: true,
  includeMitreTags: true,
};

export class TelegramService {
  private static STORAGE_KEY = 'cybernexsus_telegram_config';
  private static LOGS_KEY = 'cybernexsus_telegram_logs';

  static getConfig(): TelegramConfig {
    try {
      const saved = localStorage.getItem(this.STORAGE_KEY);
      if (saved) return JSON.parse(saved);
    } catch (e) {
      console.warn('Failed reading telegram config from localStorage', e);
    }
    return DEFAULT_TELEGRAM_CONFIG;
  }

  static saveConfig(config: TelegramConfig): void {
    try {
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify(config));
    } catch (e) {
      console.warn('Failed saving telegram config', e);
    }
  }

  static getDispatchLogs(): TelegramDispatchLog[] {
    try {
      const saved = localStorage.getItem(this.LOGS_KEY);
      if (saved) return JSON.parse(saved);
    } catch (e) {
      console.warn('Failed reading dispatch logs', e);
    }
    return [];
  }

  static appendLog(log: TelegramDispatchLog): void {
    try {
      const existing = this.getDispatchLogs();
      const updated = [log, ...existing].slice(0, 50); // Keep last 50
      localStorage.setItem(this.LOGS_KEY, JSON.stringify(updated));
    } catch (e) {
      console.warn('Failed saving dispatch log', e);
    }
  }

  /**
   * Format alert into SOC Telegram message payload
   */
  static formatAlertMessage(alert: SecurityAlert, config: TelegramConfig): string {
    const sevEmoji = alert.severity === 'CRITICAL' ? '🚨' : alert.severity === 'HIGH' ? '⚠️' : 'ℹ️';
    const mitreStr = alert.mitreTechniques.map(t => `${t.id} (${t.name})`).join(', ');

    let msg = `<b>${sevEmoji} CYBERNEXSUS EDGE SOC ALERT</b>\n`;
    msg += `<b>Incident ID:</b> <code>${alert.id}</code> (${alert.incidentId})\n`;
    msg += `<b>Title:</b> ${alert.title}\n`;
    msg += `<b>Severity:</b> <b>${alert.severity}</b> | <b>Risk Score:</b> ${alert.riskScore}/100\n`;
    msg += `<b>Affected Asset:</b> <code>${alert.affectedHost}</code>\n`;
    msg += `<b>User Account:</b> <code>${alert.affectedUser}</code>\n\n`;

    if (config.includeCvssDetails) {
      msg += `<b>📊 CVSS v3.1 Metrics:</b>\n`;
      msg += `• Base Score: <b>${alert.cvss.baseScore}</b> (${alert.cvss.severity})\n`;
      msg += `• Vector: <code>${alert.cvss.vectorString}</code>\n`;
      msg += `• Exploitability: ${alert.cvss.exploitabilityScore} | Impact: ${alert.cvss.impactScore}\n\n`;
    }

    if (config.includeMitreTags && alert.mitreTechniques.length > 0) {
      msg += `<b>🎯 MITRE ATT&CK:</b>\n<code>${mitreStr}</code>\n\n`;
    }

    msg += `<b>📝 Summary:</b>\n${alert.summary}\n\n`;

    if (alert.investigationResult) {
      msg += `<b>🧠 Local AI Hypothesis (Snapdragon ${alert.investigationResult.executionProvider}):</b>\n`;
      msg += `<i>${alert.investigationResult.attackHypothesis.substring(0, 280)}...</i>\n\n`;
    }

    msg += `<i>Generated by CyberNexsus Local Edge AI (Qualcomm Hexagon NPU - Zero Cloud Telemetry)</i>`;
    return msg;
  }

  /**
   * Dispatch alert to Telegram
   */
  static async dispatchAlert(
    alert: SecurityAlert, 
    customConfig?: TelegramConfig
  ): Promise<{ success: boolean; message: string; log: TelegramDispatchLog }> {
    const config = customConfig || this.getConfig();
    const payload = this.formatAlertMessage(alert, config);
    const sentAt = new Date().toISOString();

    // If bot token and chat ID are configured, attempt real Telegram API call
    if (config.botToken && config.chatId) {
      try {
        const url = `https://api.telegram.org/bot${config.botToken}/sendMessage`;
        const res = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            chat_id: config.chatId,
            text: payload,
            parse_mode: 'HTML',
            disable_web_page_preview: true,
          }),
        });

        const data = await res.json();
        if (data.ok) {
          const log: TelegramDispatchLog = {
            id: `tg-${Date.now()}`,
            alertId: alert.id,
            alertTitle: alert.title,
            severity: alert.severity,
            sentAt,
            status: 'SUCCESS',
            recipientChatId: config.chatId,
            payloadText: payload,
          };
          this.appendLog(log);
          return { success: true, message: 'Dispatched directly to Telegram channel via Bot API.', log };
        } else {
          throw new Error(data.description || 'Telegram API returned error');
        }
      } catch (err: any) {
        const log: TelegramDispatchLog = {
          id: `tg-${Date.now()}`,
          alertId: alert.id,
          alertTitle: alert.title,
          severity: alert.severity,
          sentAt,
          status: 'FAILED',
          recipientChatId: config.chatId,
          payloadText: payload,
        };
        this.appendLog(log);
        return { success: false, message: `Telegram API error: ${err.message}`, log };
      }
    }

    // High fidelity simulator mode (when tokens are not yet provided)
    const simLog: TelegramDispatchLog = {
      id: `tg-sim-${Date.now()}`,
      alertId: alert.id,
      alertTitle: alert.title,
      severity: alert.severity,
      sentAt,
      status: 'SIMULATED',
      recipientChatId: config.chatId || '@CyberNexsus_SOC_Alerts',
      payloadText: payload,
    };
    this.appendLog(simLog);

    return { 
      success: true, 
      message: 'Simulated dispatch successful. Message formatted and recorded in dispatch stream.', 
      log: simLog 
    };
  }
}
